[platformio]
default_envs = voicepe
src_dir = main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600

[env:voicepe]
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=1

[env:sat1]
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=0
    -D TATER_BOARD_SAT1=1
