[platformio]
default_envs = voicepe
src_dir = main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600

[env:voicepe]
board_build.cmake_extra_args = -DTATER_NATIVE_BUILD_ENV=voicepe
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=1

[env:sat1]
board_build.cmake_extra_args = -DTATER_NATIVE_BUILD_ENV=sat1
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=0
    -D TATER_BOARD_SAT1=1

[env:respeaker_xvf3800]
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions_8mb.csv
board_build.cmake_extra_args = -DTATER_NATIVE_BUILD_ENV=respeaker_xvf3800
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=0
    -D TATER_BOARD_SAT1=0
    -D TATER_BOARD_RESPEAKER_XVF3800=1

[env:s3_box]
board_build.cmake_extra_args = -DTATER_NATIVE_BUILD_ENV=s3_box
build_flags =
    -D TATER_NATIVE_PLATFORMIO_BUILD=1
    -D TATER_BOARD_VOICE_PE=0
    -D TATER_BOARD_SAT1=0
    -D TATER_BOARD_RESPEAKER_XVF3800=0
    -D TATER_BOARD_S3_BOX=1
