#pragma once

#include "driver/gpio.h"

#define TATER_BOARD_ID "satellite1"
#define TATER_FIRMWARE_VERSION "native-satellite1-0.2.3"

#define TATER_I2C_SDA GPIO_NUM_5
#define TATER_I2C_SCL GPIO_NUM_6
#define TATER_XMOS_RESET GPIO_NUM_4

#define TATER_SAT1_SPI_CLK GPIO_NUM_12
#define TATER_SAT1_SPI_MOSI GPIO_NUM_11
#define TATER_SAT1_SPI_MISO GPIO_NUM_13
#define TATER_SAT1_SPI_CS GPIO_NUM_10
#define TATER_SAT1_FUSB302B_IRQ GPIO_NUM_1

#define TATER_MIC_I2S_BCLK GPIO_NUM_8
#define TATER_MIC_I2S_WS GPIO_NUM_7
#define TATER_MIC_I2S_DIN GPIO_NUM_15
#define TATER_MIC_I2S_MCLK GPIO_NUM_16
#define TATER_MIC_SOURCE_SAMPLE_RATE 48000
#define TATER_MIC_SAMPLE_RATE 16000
#define TATER_MIC_SOURCE_BITS 32
#define TATER_MIC_OUTPUT_BITS 16
#define TATER_MIC_SOURCE_CHANNELS 2
#define TATER_MIC_OUTPUT_CHANNELS 1
#define TATER_MIC_SOURCE_CHUNK_FRAMES 480
#define TATER_MIC_CHUNK_FRAMES 160

#define TATER_SPK_I2S_BCLK GPIO_NUM_8
#define TATER_SPK_I2S_WS GPIO_NUM_7
#define TATER_SPK_I2S_DOUT GPIO_NUM_9
#define TATER_SPK_I2S_MCLK GPIO_NUM_16
#define TATER_SPK_SAMPLE_RATE 48000
#define TATER_SPK_CHANNELS 2
#define TATER_SPK_BITS 32

#define TATER_LED_PIN GPIO_NUM_21
#define TATER_LED_POWER_EN GPIO_NUM_45
#define TATER_LED_COUNT 24

#define TATER_CENTER_BUTTON GPIO_NUM_0

#define TATER_SAT1_PCM5122_I2C_ADDR 0x4D
#define TATER_SAT1_TAS2780_I2C_ADDR 0x3F

#define TATER_CAP_LINE_OUT true
#define TATER_CAP_XMOS true
