#pragma once

#include "driver/gpio.h"
#include "driver/spi_master.h"

#define TATER_BOARD_ID "s3-box"
#define TATER_FIRMWARE_VERSION "native-s3-box-0.2.2"

#define TATER_I2C_SDA GPIO_NUM_8
#define TATER_I2C_SCL GPIO_NUM_18

#define TATER_MIC_I2S_BCLK GPIO_NUM_17
#define TATER_MIC_I2S_WS GPIO_NUM_45
#define TATER_MIC_I2S_MCLK GPIO_NUM_2
#define TATER_MIC_I2S_DIN GPIO_NUM_16
#define TATER_MIC_SOURCE_SAMPLE_RATE 48000
#define TATER_MIC_SAMPLE_RATE 16000
#define TATER_MIC_SOURCE_BITS 16
#define TATER_MIC_OUTPUT_BITS 16
#define TATER_MIC_SOURCE_CHANNELS 2
#define TATER_MIC_OUTPUT_CHANNELS 1
#define TATER_MIC_SOURCE_CHUNK_FRAMES 480
#define TATER_MIC_CHUNK_FRAMES 160

#define TATER_SPK_I2S_BCLK GPIO_NUM_17
#define TATER_SPK_I2S_WS GPIO_NUM_45
#define TATER_SPK_I2S_MCLK GPIO_NUM_2
#define TATER_SPK_I2S_DOUT GPIO_NUM_15
#define TATER_SPK_AMP_EN GPIO_NUM_46
#define TATER_SPK_SAMPLE_RATE 48000
#define TATER_SPK_CHANNELS 2
#define TATER_SPK_BITS 16

#define TATER_LCD_SPI_HOST SPI2_HOST
#define TATER_LCD_SPI_CLK GPIO_NUM_7
#define TATER_LCD_SPI_MOSI GPIO_NUM_6
#define TATER_LCD_CS GPIO_NUM_5
#define TATER_LCD_DC GPIO_NUM_4
#define TATER_LCD_RESET GPIO_NUM_48
#define TATER_LCD_BACKLIGHT GPIO_NUM_47
#define TATER_LCD_WIDTH 320
#define TATER_LCD_HEIGHT 240

#define TATER_LED_COUNT 12
#define TATER_HAS_CENTER_BUTTON 0

#define TATER_CAP_LINE_OUT false
#define TATER_CAP_XMOS false
