#pragma once

#include "driver/gpio.h"

#define TATER_BOARD_ID "respeaker-xvf3800"
#define TATER_FIRMWARE_VERSION "native-respeaker-xvf3800-0.1.40"

#define TATER_I2C_SDA GPIO_NUM_5
#define TATER_I2C_SCL GPIO_NUM_6

#define TATER_MIC_I2S_BCLK GPIO_NUM_8
#define TATER_MIC_I2S_WS GPIO_NUM_7
#define TATER_MIC_I2S_DIN GPIO_NUM_43
#define TATER_MIC_SOURCE_SAMPLE_RATE 48000
#define TATER_MIC_SAMPLE_RATE 16000
#define TATER_MIC_SOURCE_BITS 32
#define TATER_MIC_OUTPUT_BITS 16
#define TATER_MIC_SOURCE_CHANNELS 2
#define TATER_MIC_OUTPUT_CHANNELS 1
#define TATER_MIC_SOURCE_CHUNK_FRAMES 480
#define TATER_MIC_CHUNK_FRAMES 160

#define TATER_SPK_I2S_BCLK GPIO_NUM_8
#define TATER_SPK_I2S_WS GPIO_NUM_7
#define TATER_SPK_I2S_DOUT GPIO_NUM_44
#define TATER_SPK_SAMPLE_RATE 48000
#define TATER_SPK_CHANNELS 2
#define TATER_SPK_BITS 32

#define TATER_LED_COUNT 12
#define TATER_HAS_CENTER_BUTTON 0

#define TATER_CAP_LINE_OUT true
#define TATER_CAP_XMOS true
