#pragma once

#include "driver/gpio.h"

#define TATER_BOARD_ID "voice-pe"
#define TATER_FIRMWARE_VERSION "native-voicepe-0.1.39"

#define TATER_I2C_SDA GPIO_NUM_5
#define TATER_I2C_SCL GPIO_NUM_6
#define TATER_XMOS_RESET GPIO_NUM_4

#define TATER_MIC_I2S_BCLK GPIO_NUM_13
#define TATER_MIC_I2S_WS GPIO_NUM_14
#define TATER_MIC_I2S_DIN GPIO_NUM_15
#define TATER_MIC_SAMPLE_RATE 16000
#define TATER_MIC_SOURCE_BITS 32
#define TATER_MIC_OUTPUT_BITS 16
#define TATER_MIC_SOURCE_CHANNELS 2
#define TATER_MIC_OUTPUT_CHANNELS 1
#define TATER_MIC_CHUNK_FRAMES 320

#define TATER_SPK_I2S_BCLK GPIO_NUM_8
#define TATER_SPK_I2S_WS GPIO_NUM_7
#define TATER_SPK_I2S_DOUT GPIO_NUM_10
#define TATER_SPK_AMP_EN GPIO_NUM_47
#define TATER_SPK_SAMPLE_RATE 48000
#define TATER_SPK_CHANNELS 2
#define TATER_SPK_BITS 32

#define TATER_LED_PIN GPIO_NUM_21
#define TATER_LED_POWER_EN GPIO_NUM_45
#define TATER_LED_COUNT 12

#define TATER_CENTER_BUTTON GPIO_NUM_0
#define TATER_MUTE_SWITCH GPIO_NUM_3
#define TATER_ENCODER_A GPIO_NUM_16
#define TATER_ENCODER_B GPIO_NUM_18

#define TATER_CAP_LINE_OUT false
#define TATER_CAP_XMOS true
